### ISSUE TITLE
Add contributing guide

### ISSUE THREAD

**Issue by richardcase** [rancher-sandbox/rancher-turtles-docs#4]
Lets add a contributing guide to help attract contributions from the wider community. We can use some of the existing instructions in the README.

We should also cover non-coding contributions.

**Comment by furkatgofurov7** [comment]
@richardcase https://github.com/rancher-sandbox/rancher-turtles/pull/96 added the doc to the rancher-turtles repo, but I should admit it is not generic and specific to that repo. Do you think we still need a separate CONTRIBUTING file for this repo or we can just point from this repo to the one in rancher-turtles?

**Comment by richardcase** [comment]
> @richardcase [rancher-sandbox/rancher-turtles#96](https://github.com/rancher-sandbox/rancher-turtles/pull/96) added the doc to the rancher-turtles repo, but I should admit it is not generic and specific to that repo. Do you think we still need a separate CONTRIBUTING file for this repo or we can just point from this repo to the one in rancher-turtles?

@furkatgofurov7 - what do you think to adding the contributing guide to the docs site instead and point to it from rancher-turtles & rancher-turtles-ui contributing files?
